issue-guide.md
issues-guide.md

Fixes #10 
Fixes https://github.com/ipfs/infrastructure/issues/8
Added in a guide for collaborators and non-collaborators on how Github issues are handled and processed.

Issues guide

---

contribution-guidelines.md

contribution-guidelines: fix link to setup_commit_msg_hook.sh

---

contribution-guidelines.md
docs/amending-commits.md

This could help people improve their commits after tests or code reviews complain about them.

Add amending-commits.md

---

README.md

@jbenet What do you think? 
After this has been merged, the calendar should also be added to ipfs/ipfs and ipfs.io/#documentation.

Added calendar link and instructions

---

contribution-guidelines.md
go-contribution-guidelines.md

This solves an issue brought up in https://github.com/ipfs/go-ipfs/pull/1734; how do we maintain similar standards over many repositories using the same language without duplicating language guidelines? All go repositories should now point to this file, and we can update it accordingly. 
Most of this was pulled from https://github.com/ipfs/go-ipfs/blob/master/contribute.md. I have a branch ready to strip that file and point here if this is merged.

Added go-contribution-guidelines.md

---

contribution-guidelines.md

We will not likely be doing this. There is a project directory with 30+ repositories, and I feel that maintaining a list here would add too much overhead. I think removing this comment is the right thing to do.

Removed comment about adding a list of maintainers

---

contribution-guidelines.md

I think this should make commit sign offs a bit more approachable.

Made the commit sign off messaging easier

---

README.md

I think that people may not check the issues. Perhaps we should set up an email where people can send their addresses, so that they do not need to publicly post in this issue? swag@ipfs.io? I am happy to help send out swag, too.
Related to https://github.com/ipfs/community/issues/11.

Added a swag section

---

contributing.md
contribution-guidelines.md

I added a "Helping in other ways" section, and moved the commit sign off message to go-ipfs. This is only used in go-ipfs. I have moved it to the contribution guidelines for that repository, and have opened PR. I ran into at least one contributor who was intimidated by this section, and it is not currently mandatory for all repositories (although it potentially should be).

Editing contributing

---

contribution-guidelines.md
js-contribution-guidelines.md

Added js guidelines

---

contributing.md

This should make it easier to highlight the help wanted label to people. See https://github.com/ipfs/community/issues/94

Added Dive right in section

---

js-project-guidelines.md

Final copy edits

---

docs-styleguide.md

Bash prompts and single-word heading capitalization

---

contribution-guidelines.md

We want to have a section for each possible problem that GitCop can report,
because now all the error messages can be configured in GitCop, and we want
them to contain a different link depending on the problem.
License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>

contribution-guidelines: add sections for GitCop reported problems

---

contribution-guidelines.md

Link to JS contribution guidelines was pointing to a file that doesn't exist

fix link to JS contrib guidelines

---

js-commit-guidelines.md

This is a first draft as discussed in https://github.com/dignifiedquire/aegir/issues/30. 
It is very much based on the referenced angular commit convention. 
Currently there is no mentioning of signing commits. The reason for this is that we would need to change the tooling first to remove those signatures from the changelog. So I want us to be sure we need and want to add this.
cc @diasdavid @VictorBjelkholm @nginnever

Draft of js git commit convention

---

docs-styleguide.md

As previously discussed in https://github.com/ipfs/go-ipfs/pull/3018 . See https://www.grammarly.com/handbook/grammar/verbs/8/simple-present-tense-present-indefinite/ for a description of this tense.
@thomas-gardner pointed out that using simple present 3rd-person singular tense, rather than imperative mood, is contrary to the practices of various other programs/projects. So we may want to follow that, instead. I made it this way to start with, because I already took the time to make all the taglines consistent with this way. But I'm open to switching.

Require simple present 3rd-person singular tense for taglines

---

contribution-guidelines.md

This comes directly from ipfs/go-ipfs#3166, and @Kubuxu. I have added it here and edited it slightly for language.

Adding a revert policy

---

README.md

#50 was closed, pointing to #175 avoids confusion.

Update stickers issue

---

README.md

We dont use this section, or update it, and I am not sure that the information is relevant to anyone. This PR removes it.

Remove Events Section in README

---

js-project-guidelines.md

This is in relation to ipfs/community#225.

Added Captain explanation

---

examples/ipfs-README.md

This adds an example IPFS README that conforms to standard-readme and should be able to help with making new READMEs for IPFS repositories. It is language agnostic. However, it is based on a request by the JS team (specifically, @diasdavid) in https://github.com/ipfs/community/issues/225#issuecomment-272419143

Add example IPFS README

---

js-project-guidelines.md

This adds a note about aegir-lint. See https://github.com/ipfs/community/issues/225#issuecomment-277132527

Add lint note to javascript guidelines

---

js-project-guidelines.md

This references the Awesome Documentation effort. See https://github.com/ipfs/js-ipfs/issues/615

Added Documentation note to js-guidelines

---

examples/readme-templates/libp2p.md

I realize that there isn't one. This should change that.

Adding a libp2p example readme

---

decisions/community-forum-platform.md

**We will finalize the decision on Friday 17 March 2017** and write the conclusion into this document.
This document gathers all of the needs, factors to consider, and relevant proposals around creating a community forum for IPFS and its related projects. It's structured to allow final discussions about this topic so that we can make a decision about how to proceed. The information in the document was sourced from all the related issues and notes from a couple public calls (see references).
If you have modifications to the proposal, modifications to the background information or if you want to block this proposal and argue for an alternative, please speak up before Friday.
References:
* **original discussion** Discourse - Better community building …

Decision Document: Creating a Community Forum for IPFS and Related Projects

---

js-project-guidelines.md

This is "completely out of date", according to @diasdavid in https://github.com/ipfs/community/issues/225#issuecomment-272419143. I remove it here. What should go in its place?

Remove build section from js guidelines

---

contributing.md

Add " label:"help wanted" to search parameters, when searching for To-Dos. This performs the search: label:"difficulty:easy" label:"help wanted" user:IPFS is:open which shows all issues at the intersection of label:"difficulty:easy", label:"help wanted", user:IPFS, and is:open.

Update Github Issue Search Hyperlink to find easy issues.

---

contributing.md

Fixed email with subject hyperlink, the spaces did not render the link correctly.

fix email link

---

README.md

Change calendar link timezone from America/New_York to UTC to avoid confusion and import conversion errors, in light of move to daylight-immune UTC discussed in All Hands Call https://github.com/ipfs/pm/issues/584

Change calendar link timezone from New_York to UTC

---

js-code-guidelines.md

@diasdavid gave some insight as to the preferred use of `~` vs `^` in `package.json` dependency versions in [this PR](https://github.com/ipfs/js-ipfs-api/pull/734#issuecomment-383852801) so let's add it to the JS guidelines to make sure it doesn't get lost.

docs: Add section about prefered dependency version strategy

---

js-code-guidelines.md

Doesn't require external module or any interaction after first setup.
Also renamed it to not be confused with "signing commits"

Simpler automatic git signoff

---

js-code-guidelines.md

The section in the README mentioning the Lead Maintainer is not called
"Maintainer", but "Lead Maintainer".

The README section is called `Lead Maintainer`

---

docs/licensing-policy.md

This is based on discussion from #139, ipfs/faq#165, and ipfs/ipfs#319. In trying to get the docs repo all set, it seemed like we should have whatever the current policy is clearly documented.
Feel free to edit or change whatever doesn’t seem right here.

DRAFT: Document our licensing policy

---

js-code-guidelines.md

If the Lead Maintainer and Tech Lead is the same person, another
Tech Lead should also have permission to publish a module. This
reduces risks.

Make sure all modules have two publishers

---

js-code-guidelines.md

- Use `leadMaintainer` as the package.json property.
- Fix the TOC link for the sign-off section.
- Update pre-commit link name to match module name. (precommit is the name of different module that does a similar thing)
- Sign-off "User Name" should be your legal name.

docs(js): fix minor errors in js-code-guidlines

---

js-code-guidelines.md

The `Supported Versions` headline wasn't formatted correctly.

Fix formatting

---

code-of-conduct-procedures-for-events.md
code-of-conduct.md

adds procedures from [Code4Lib Code of Conduct](https://github.com/code4lib/code-of-conduct) for handling reports of CoC violations at in-person events/meetings/conferences
This has mostly the same stuff as PR #325 but is slightly simplified.

add procedures for code of conduct violations at events

---

docs/licensing-policy.md

I think this was a typo on my part initially — we still have to say "copyright" before the "(c)" for the CC license :P

Add missing words in suggested README text for licensing policy

---

DOCS_STYLEGUIDE.md

This adds several more general guidelines (based on examples I’ve seen while working on IPFS docs for the last few months), a list of words to avoid, and links to additional resources for learning more about good, plain-language writing.

Add more guidelines & links to docs styleguide

---

CONTRIBUTING.md

These have been deprecated for a while.

remove out of date issue trackers and direct users to the forums

---

DOCS_STYLEGUIDE.md

It looks like someone might have attempted to re-style all the bullet points in the docs styleguide to dashes by doing a simple find-and-replace in #346. Unfortunately, that also affected asterisks that were for italics (not bullet points), thereby breaking the italics. This switches those back.

Fix italics/asterisks that got converted to dashes

---

ROADMAP.md

After a lot of planning with the rest of the IPFS project the short terms goals and timeline for the Community WG have been defined.
I've adapted our prior roadmap into a format that is much more understandable by people who haven't been involved in the IPFS planning process. Terms like "KPI" have been remove and replaced with more descriptive language like "Success Criteria." 
I've also made sure that each project has at least one link someone can go to if they are interested in contributing to the project at what ever stage it is at.

Community Roadmap

---

okrs/2019-q1.md

I'm trying something a little different with the Q1 OKR's this time around. Instead of a spreadsheet I'm going to see if we can use a markdown file in the repo.
This is an experiment, it may succeed or it may fail horribly :) It's certainly **not** easier to write OKR's in this format, but it does add something to the discoverability and once I put a link to an active issue in here for every OKR it'll be a lot more useful.

[WIP] 2019 Q1 OKR's

---

okrs/2019-q1.md

- Update OKR scope based on discussion with @mikeal and @marvinammori. Revised goals is to get articles ready for publication, but does not include publication launch, which will be handled by the comms team once hired.

Update publication OKR

---

CONTRIBUTING.md

This PR removes confusing sentence that mentioned sending email without providing email address.
(and I assume @RichardLitt is no longer DRI for this)

docs(i18n): cleanup

---

CONTRIBUTING.md

added official docs going through `git commit --amend`. 
The original file is gone.
License: MIT
Signed-off-by: Dan Shields <danwshields@gmail.com>

broken link to amend commit -- a suggestion

---

CONTRIBUTING_JS.md

This adds section on defining and reusing Error Codes, as requested in https://github.com/ipfs/js-ipfs/pull/2547#discussion_r336922054
Used `Errors` from `interface-datastore` as an example.

Add section on "Error Codes" to CONTRIBUTING_JS.md

---

CONTRIBUTING.md

Apparently it is expired. I have no knowledge of a new key being generated.

Contributing: remove gpg key.

---

CONTRIBUTING.md

It is more effective to just ping the maintainer.

Contributing: remove irc mention

---

README.md

Planning to bring this back in the future, but for the time being this email address is not monitored. Stay tuned!

Remove swag request link for the time being

---

CONTRIBUTING_JS.md

I found "most recent LTS" a bit vague. With this change you can go to
https://nodejs.org/en/about/releases/ and clearly see which versions
are supported.
I hope that reflects what the original sentence tried to say. That would
mean that as of today, we support v12 and v14. We **won't** support v10.

Clarifying supported Node.js versions

---

CONTRIBUTING_JS.md

Per sync discussion, this PR adds JS documentation contributing guidelines based on JSDoc based types.
The general decision is that type definition should be placed on the top of JS files. 
cc @ipfs/js-core-team

chore: add js documentation contributing guidelines

---

projects/ipfs-chat.md

Project Repo: https://github.com/SomajitDey/ipfs-chat

[Project Submission] ipfs-chat

---

projects/IPNS-Link.md

If merged, we intend to apply for a Next Step grant in order to 
- attract excellent developers
- scale up the existing public IPNS-Link-gateway at [ipns.live](https://www.ipns.live)
- host more public gateways
- host public IPFS relays
- create a robust `.ipns` registry

[Project Submission] IPNS-Link

---

README.md

no longer deprecating - this is a repo we actually need to be actively using.  core message still valid - this needs to be cleaned up a lot, so changed to warning message also updated repo purpose in readme

changed deprecation notice

---

CONTRIBUTING_JS.md

greenkeeper is pointing to sync, and dependabot is what most open-source and PLN projects use

docs: update dependency management recommendations

---

CONTRIBUTING_JS.md

Updates contributing doc to remove references to obsolete tools, add references to Unified CI and clarify supported platforms
Refs: https://github.com/ipfs/helia/issues/113

docs: Update CONTRIBUTING_JS.md

---

CONTRIBUTING.md

This is to deter parties submitting many trivial changes in order to artificially inflate github contribution metrics. 
Also, as stated, cuts down on the number of tiny PRs and helps us better count functional contributions.

Update CONTRIBUTING.md with note about drive-by changes
