README.md
There was a lack of order in the list people. This pull request is dependent upon my previous pull request #4
=> Alphabetically increasing order

README.md
=> Fix the links in the readme

contribution-guidelines.md, project.md
=> Fixed a couple of broken links

contribution-guidelines.md
Connected to https://github.com/ipfs/infrastructure/issues/8
I've updated the contribution guidelines to include further instructions on what goes into a pull request description. Specifically on the use of keywords such as closes, resolves, fixes, and connects.
=> Contribution guidelines concerning pull requests

dev/tools/hooks/setup_commit_msg_hook.sh, docs/commit-message.md, docs/developer-certificate-of-origin
This will let us use [GitCop](https://gitcop.com) to check the commit messages.
=> Add DCO and commit-message.md

docs/LICENSE, docs/commit-message.md
There were some broken links in:
https://github.com/ipfs/community/blob/master/docs/commit-message.md
This should fix them.
=> Commit messages more

contribution-guidelines.md
=> All commits must pass

contribution-guidelines.md
Resolved the duplicate sign and release section pointed out in the discussion of the merged pull request #30
=> The sign and release section got duplicated

docs/amending-commits.md
This should fix issue https://github.com/ipfs/community/issues/43
=> amending-commits: add that force pushing is ok

README.md
License: MIT
Signed-off-by: Christian Couder <chriscool@tuxfamily.org>
=> README: add Chriscool's Twitter account

README.md
=> Added self to People list

README.md
To make it clear this isn't for code topics. Result of talks in https://github.com/ipfs/community/issues/69.
=> Added note about meta-non-code discussions

dev/tools/hooks/setup_commit_msg_hook.sh
This should make this script a bit easier to use.
=> Added echo statements and .git check

contributing.md
=> Added the gif and links to the top of contrib

docs-styleguide.md
This should help with the API spec and with rewriting the Go mans.
=> Added a docs styleguide

dev/tools/github/githubLabels.json, dev/tools/github/repos.js
=> Added repos tools

docs-styleguide.md
=> Added default notice

README.md
Goal of logging all the events that happened or that are scheduled by the IPFS community, so that people can have track of where to find more about IPFS in person.
The list is not complete yet, please add all that you come to your head
We can also grab this list and feed it to the website to show what are the next events, similar to what Nodeschool does
=> Idea: IPFS Community Events

dev/tools/hooks/setup_commit_msg_hook.sh
Seems like this might be helpful.
=> Added note about location

contribution-guidelines.md
Explain what a DCA is, and clarify a few sentences.
=> contribution-guidelines: small updates

contributing.md
=> Added note about translations

contributing.md
=> Added link to support repos

code-of-conduct.md
See https://github.com/ipfs/community/issues/129
=> Added a note about IRC ops to the CoC

README.md, code-of-conduct.md, contributing.md, contribution-guidelines.md
=> Add Table of Contents to long files

LICENSE, README.md
See https://github.com/ipfs/community/issues/124#issuecomment-226484452
=> Standardized Readme, added License

contributing.md
=> Moved Community Guidelines up in Contributing

code-of-conduct.md
Added a note about the tl;dr in case anyone is confused, and fixed a spelling error, removed a whitespace, and uppercased IPFS.
=> Small code of conduct edits

contribution-guidelines.md
Per https://botbot.me/freenode/ipfs/2016-09-04/?msg=72461333&page=1
=> Add a request to mention forgotten PRs in #ipfs

organizations.md
See this issue, which asked that this be documented and stored: https://github.com/multiformats/php-multihash/issues/1#issuecomment-237933659
=> Added an organizations document

how-to-organize-a-meetup.md
=> Add a guide on how to organize a Meetup

README.md
This points new users to the PM calls. Closes #196
=> Added note about ipfs/pm

contribution-guidelines.md
Updated to show Needs Review - we dont use LFCR anymore. And added my name instead of @jbenet for requests for help with merges.
=> Change Code Review and Merge sections

README.md
=> Added ref to reading-list

README.md
=> Add ipfs/reading-list to about section

js-project-guidelines.md
See #225. @dignifiedquire can we add a check to aegir to make this throw a flag?
=> Add note about tildes over carrots

js-project-guidelines.md
=> Add section on Pull Requests

dev/mkmrconfig.sh
Ported over from ipfs/devtools#1 -- not porting over the prose for now.
=> Add myrepos script

contribution-guidelines.md
License: MIT
Signed-off-by: Tarnay Kálmán <kalmisoft@gmail.com>
=> signway typo in contribution-guidelines.md

js-code-guidelines.md
=> docs: adds supported node versions

README.md
=> Compress contributors grid image

js-code-guidelines.md
Documents the intention behind ipfs/aegir#231
=> docs: add clause explaining when to bend the dep version rules

CONTRIBUTING_GO.md
https://github.com/ipfs/go-ipfs/blob/master/contribute.md
=> docs: Draft of merging this with the go-ipfs contribution guidelines

CONTRIBUTING_GO.md
=> Add Golang PR review section

CONTRIBUTING_GO.md
cc @ipfs/go-team
This is a proposal, please discuss. If you don't think this answers questions like "can I merge this?", "can I change this?", etc., please say so.
Also, it would be *awesome* to get some examples here.
=> [RFC] add contributor principles and merge policy

CONTRIBUTING_JS.md
Moved to https://github.com/ipfs/team-mgmt/pull/819
=> docs: move Lead Maintainer Protocol to Team Management

okrs/2019-q1.md
Let's do another round of iteration on the Q1 OKR's.
I'll start things off by adding priorities to all the existing ORK's.
=> Q1 2019 OKR Round 2

okrs/2019-q1.md
Some intitial scoring. @terichadbourne can you add your scoring in this branch?
I’m also working on re-prioritizing the Community WG in this PR. In this quarter, and next, we need to re-focus our priorities on either **new users** or **new contributors**. Additional PR’s to follow with new work items and priorities but, already, I’m cutting the automation at the bottom as it addresses long term contributors and is definitely not within this new priority scope.
=> [WIP] Mid-Quarter Scoring and Re-Prioritizing

okrs/2019-q1.md
- Add Teri's final results for Q1 KRs
=> Add Teri's Q1 OKR final scores

README.md
- Add ProtoSchool info 
- Update sticker request process since the issue referenced has been closed
=> Add ProtoSchool, correct swag request process

CONTRIBUTING_GO.md
Update the quick guide to use go modules.
=> docs: update quick guide to use go modules

projects/yaytso.md
Hope this is right for Next Step submission!
=> [Project Submission] Yaytso

projects/nftwitch.md
Submitting NFTwitch to the IPFS community as part of the Next Steps grant.
=> [Project Submission] NFTwitch

projects/TrueRaffle.md
add project submission about TrueRaffle
=> [Project Submission] TrueRaffle

projects/niftyroyale.md
Adding Nifty Royale to Projects
=> [Project Submission] Nifty Royale

projects/luxurify.md
=> [Project Submission] Luxurify

projects/pdarm.md
Adding Parametric Digital Asset Risk Management project submission
=> [Project Submission] Parametric Digital Asset Risk Management

projects/DungeonCrawler.md
Hey @autonome , hope you are having a great day. I have created a new PR as I happened to delete the previous one by mistake, as I had created the markdown file in the templates directory last time. I have implemented the changes that were requested last time. Thanks.
Cheers 
Elio
=> [Project Submission] Dungeon crawler

projects/Monaliza.md
=> [Project Submission] Monaliza

projects/LandMine.md
=> Landmine markdown file

projects/immutable.md
Immutable is a project built using IPFS at CivHacks. The project won the best beginner track in CivHacks and we are interested in Next Step Grant programme.
=> Adding Immutable in the projects for Next Step Grants

projects/Ownft.md
Adding our project to the IPFS Community Showcase for https://github.com/protocol/grants/blob/main/nextstep.md
=> Ownft project

projects/Fractio.xyz
=> [Project Submission] Fractio.xyz

projects/DungeonCrawler.md
As suggested previously, our team details have been updated.
=> Dungeon Crawler - team details updated

projects/mbondX.md
created project file mbondX.md
=> [project submission] mbondx

projects/Meta Manager.md
Added the project profile of Meta Manager.
=> [Project Submission] Meta Manager

projects/The Convo Space.md
Stoked to add The Convo Space to the IPFS ecosystem of projects.
=> [Project Submission] Add The Convo Space

projects/nft-import.md, templates/nft-import.md
NFT import is a WordPress Plugin allowing to import your NFTs in your WordPress media library, to include them in your website
=> [Project Submission] NFT Import

projects/PassVault.md
Hello there,
We already have a beta version of PassVault in our repository. In the coming days, we will be adding more features to it and provide it with clear documentation and contribution guide.
=> [PROJECT SUBMISSION] Adding PassVault to Projects

projects/IPFSfB.md
IPFSfB: https://github.com/ipfs/community/discussions/574
=> [Project Submission] IPFSfB

projects/box.md
Project box is taking one step toward web3. This files contains the details of this project
=> [Project Submission] box

projects/4EVERLAND.md
docs(projects): create 4EVERLAND.md
=> [Project Submission] 4EVERLAND

projects/Evido.md
Greetings
We already have developed a version of Evido which can be found in our repository. We will be adding more features and deploy the application .
=> [PROJECT SUBMISSION] Adding Evido to Projects

projects/IPLDDistributedDatasets
Hello! I have put together a demo, but in the coming weeks, I am planning to flesh out the documentation and create tooling to help build and store datasets using IPLD.
=> [Project Submission] Create IPLD Distributed Datasets

projects/Esteroids.md
We are building Esteroids, it's an ENS+IPFS React app to explore and search ENS+IPFS websites.
=> [Project Submission] Esteroids

projects/HubShare.md
=> [MicroGrant]-HubShare

projects/CommunityGarden.md
Dear community,
I followed the instructions provided to add my project to the IPFS Community Showcase. 
Looking forward to your thoughts 🙂
=> [Project Submission] - Community Garden

projects/IPNSGoServer.md
My submission for nextsteps grant
=> [Project Submission] IPNSGoServer

projects/ETHmySong.md
This project won bounties in Polygon BUIDLit Hackathon, as a next step this is being submitted to Microgrants to scale it further.
=> [Project Submission] ETH My Song

projects/Creativerse.md
A truly decentralized Minecraft protocol where you own plots of land as NFTs, and each NFT stores the block data of that plot. This allows anyone to run a Creativerse server, enabling it to be a truly decentralized server. 
ETHGlobal NFTHack 2022 Finalist
https://showcase.ethglobal.com/nfthack2022/creativerse-minecraft-on-ethereum
Twitter: https://twitter.com/CreativerseMC
Discord: https://discord.gg/FHAZcVfxDn
=> [Project Submission] The Creativerse

projects/chanceofxyz.md
=> [Project Submission] chanceOf.xyz

projects/BlockchainTicketing.md
We built a decentralised events marketplace for the NFT Hack by Filecoin and Encode.
=> [Project Submission] Blockchain Ticketing

projects/MashApp.md
This project won Best Decentralized Media Hack 1st Place in Web3Jam. As a next step this is being submitted to MICROGRANTS to scale it further
=> [Project Submission] MashApp

projects/DeStore.md
Hello Filecoin team!
I want to Showcase my project.
I would also like the DeStore updates to be featured in the Filecoin newsletter.
=> [Project Submission] DeStore

projects/Lifefram.md
We're building a global decentralized database to store records of the deceased for 300 years and beyond, powered by IPFS. Knowledge should last forever, including the knowledge of us. Grand prize winner of Babylon 2.0 hackathon.
=> [Project Submission] Lifefram

projects/Dspyt-NFTs.md
Dspyt-NFTs is an interactive web application built with ReactJS to upload and view images. The application interacts with Filecoin and IPFS. In particular, **nft.storage** provides an access via api for the application to store files.
Further we consider to add minting NFTs in the application and generating metadata based on Artificial Intelligence.
[NFT hack 2022 || ETHGlobal](https://showcase.ethglobal.com/nfthack2022/dspyt-nfts)
[Live Demo](https://ipfs-personal-gallery.vercel.app/)
[Dspyt-NFTs](https://github.com/dspytdao/Dspyt-NFTs)
=> [Project Submission] Dspyt-NFTs

projects/NetSepio.md
Browser Extension to detect cyber threats and label websites/domains as Spam, Malware, Spyware, Advertisements, etc.
=> [Project Submission] NetSepio

projects/py-is_ipfs.MD
Thank you for reviewing my submission. I'm stoked to contribute to the community.
=> [Project Submission] py-is_ipfs

projects/TrueBlocks.md
=> Update expired Discord link

.github/ISSUE_TEMPLATE/open_an_issue.md, CONTRIBUTING.md, SECURITY.md
To mention how abuse reports should be routed.
=> Update security section of CONTRIBUTING.md
